### ISSUE TITLE
Build dependencies not explicitly mentioned in the README

### ISSUE THREAD

**Issue by jasonhemann** [quasarbright/PongChamp#3]
README mentions correct development libraries, but does not say what those are. I found I had to install at least the following packages from brew on my OSX 10.15.7 environment:

# To `make linux`
- `sdl2_ttf`
- `sdl2_mixer`
- `sdl2`
- `sdl2_image`

I found that I also needed `mingw-w64` to proceed for the windows target.

**Comment by RyanRio** [comment]
To add to this SDL and Windows is a whole other monster, the future engine will be opengl in any case, but we'll still have to make sure to wrap it up in the executable so the user doesn't have to have libraries installed.
