### ISSUE TITLE
implement exceptions + try/catch

### ISSUE THREAD

**Issue by RyanRio** [quasarbright/PongChamp#6]
Currently exceptions and exception handling is completely unimplemented. However, parts of the interpreter can be extended to support this. `Break`, `Continue`, and `Return` are all statements that have obvious parallels to exceptions. In a similar manner to `Break`, an exception should bubble up to its nearest catch that catches that specific exception, and then execute the code within the catch branch.

At its simplest the syntax for this could be something like:
```js
try {
    throw ExceptionType
}
catch ExceptionType {

}
```

If no catch branch is hit, then the program ends, with the interpreter displaying the error.

**Comment by quasarbright** [comment]
We add a case to the RuntimeError type for user-runtime errors. We should really distinguish between actual runtime and internal runtime errors, but whatever. If we do that, we can use the built-in try catch constructs provided by `ExceptT` in `mtl`

Semantics:

For now, exceptions are just values that are thrown. And when you catch, you just examine the value and do stuff with it.

Example:

```js
function go() {
  throw "oopsie"
}

function main() {
  try {
    go()
    print("this won't get printed")
  } catch e {
    print(e)
  }
}
main()// should only print "oopsie"
```
